# Generated by Django 5.2.7 on 2025-10-22 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('costo_mensual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('acceso_limitado', models.BooleanField(default=False)),
                ('acceso_entrenador', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id_miembro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('membresia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_miembros.membresia')),
            ],
        ),
    ]
